"""アプリ全体で共通利用する既定値。"""

# Network diagnose defaults
DEFAULT_DNS_TIMEOUT_SEC = 3.0
DEFAULT_HTTP_TIMEOUT_SEC = 5.0
DEFAULT_NETWORK_CHECK_COUNT = 3
DEFAULT_MAX_AVG_LATENCY_SEC = 1.2

# Web automation defaults
DEFAULT_VOLUME_PERCENT = 40
DEFAULT_WEB_WAIT_TIMEOUT_SEC = 20
DEFAULT_CLICK_WAIT_SEC = 1.0
DEFAULT_TAB_STEP_WAIT_SEC = 1.0
DEFAULT_RELOAD_INTERVAL_MINUTES = 15



